name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scipy=1.13.1
  - numpy>=1.20
  - pandas>=1.3
  - pytest
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - databricks_cli==0.8.7

