main:
  components_repository: "https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#components"
  project_name: "nyc_airbnb"
  experiment_name: "pipeline_development"
  steps: "all"

etl:
  sample: "sample1.csv"
  min_price: 10  # dollars
  max_price: 350  # dollars

data_check:
  kl_threshold: 0.2

modeling:
  # Fraction of data to use for testing
  test_size: 0.2
  # Fraction of remaining data to use for validation
  val_size: 0.2
  # Random seed for reproducibility
  random_seed: 42
  # Column to use for stratification (use "none" for no stratification)
  stratify_by: "neighbourhood_group"
  # Maximum number of features for the TFIDF applied to the name column
  max_tfidf_features: 5
  # Target variable in the dataset
  target: "price"
  # Numerical features
  numerical_features:
    - "latitude"
    - "longitude"
    - "minimum_nights"
    - "number_of_reviews"
    - "reviews_per_month"
    - "calculated_host_listings_count"
    - "availability_365"
  # Categorical features
  categorical_features:
    - "neighbourhood_group"
    - "room_type"
  # Date features
  date_features:
    - "last_review"
  # RandomForestRegressor parameters
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 4
    min_samples_leaf: 3
    n_jobs: -1  # Use all cores
    criterion: "squared_error"
    max_features: 0.5
